class SupabaseSecrets {
  static const supabaseUrl = 'https://loqpecxsoxzjhlzgsbci.supabase.co';
  static const supabaseAnonkey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvcXBlY3hzb3h6amhsemdzYmNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjYyNzI4NTIsImV4cCI6MjA0MTg0ODg1Mn0.gff3N_vwo4GGeMqnwyZXmCIQtiOjxR2esLEeiVcFfjQ';
}